### ISSUE TITLE
Related project tested for interop

### ISSUE THREAD

**Issue by rmhrisk** [rynomad/subtle#18]
@rynomad thought you may find interest in this native polyfil we did for node - https://github.com/PeculiarVentures/node-webcrypto-ossl

I did some interop testing with your library and found no issues.

**Comment by mitar** [comment]
We are just considering switching to `node-webcrypto-ossl`, found some features which are not yet supported, but are in process.

My main current issue is that this library seems pretty slow (5 ms for 100 bytes of data to be encrypted/decrypted for symmetric key). I hope `node-webcrypto-ossl` works better. :-)

**Comment by mitar** [comment]
We managed to switch to `node-webcrypto-ossl`. Our crypto test now takes 30 ms instead of 80 ms.

**Comment by rmhrisk** [comment]
I'm surprised the difference was so small what was the specific operation?

**Comment by mitar** [comment]
What do you mean so small? This is a series of operations, not just one. Mostly establishing ECDH key and then using it for encryption/decryption. For me this is huge improvement. You think it should be even more?

**Comment by rmhrisk** [comment]
I had not benchmarked any of the JS crypto implementations but I had expected them to be slower, while this is a big improvement I would have expected closer to 4x.

What operation is being benchmarked?

Did you measure performance in chrome or Firefox using their native webcrypto a?

**Comment by rmhrisk** [comment]
Sorry I should have asked what ECDSA operation and key size

**Comment by mitar** [comment]
But this package also uses C code?

We use ECDH and P-256.

**Comment by mitar** [comment]
Also, this includes some networking and so on. So this is our end-to-end message encryption between client and server. No encryption on the ping/pong takes around 4 ms. Adding encryption on the channel makes it now around 30 ms, while before it was 80 ms.

**Comment by rmhrisk** [comment]
I see so that's not pure crypto benchmark, makes sense then. Thanks :)
